import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { HelloRequest } from '../api/hello_pb'
import { HelloServiceClient } from '../api/HelloServiceClientPb' 

const Home: NextPage = () => {
  const [name, setName] = useState('')
  const [age, setAge] = useState(0)
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')

  const handleChangeName = (e: React.ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value)
  }
  const handleChangeAge = (e: React.ChangeEvent<HTMLInputElement>) => {
    setAge(Number(e.target.value))
  }
  const handleChangeEmail = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value)
  }

  const onClick = async () => {
    const req = new HelloRequest()
    console.log(req);
    req.setName(name)
    req.setAge(age)
    req.setEmail(email)
    const client = new HelloServiceClient("http://localhost:8080")
    const res = await client.sayHello(req, {})
    setMessage(res.getMessage())
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App　& gRPC-Web & go</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Create Next App / gRPC-Web / go
        </h1>

        <div>
          <input 
            type="text"
            value={name}
            onChange={handleChangeName}
          /> 
          <input 
            type="number"
            value={age}
            onChange={handleChangeAge}
          /> 
          <input 
            type="text"
            value={email}
            onChange={handleChangeEmail}
          /> 
          <button onClick={onClick}>Send</button>
          <p>{message}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
