import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { HelloRequest } from '../api/hello_pb'
import { HelloServiceClient } from '../api/HelloServiceClientPb' 

const Home: NextPage = () => {
  const [title, setTitle] = useState('')
  const [task, setTask] = useState('')

  const [message, setMessage] = useState('')

  const handleChangeTitle = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTitle(e.target.value)
  }
  const handleChangeTask = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTask(e.target.value)
  }

  const onClick = async () => {
    try {
      const req = new HelloRequest()
      req.setTitle(title)
      req.setTask(task)
      const client = new HelloServiceClient("http://localhost:8080")
      const res = await client.sayHello(req, {})
      setMessage(res.getMessage())
    } catch(e) {
      alert("oops!")
      console.log(e);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>react*go TODO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          React * Go TODO
        </h1>

        <div>
          <input 
            type="text"
            value={title}
            onChange={handleChangeTitle}
          /> 
          <input 
            type="textarea"
            value={task}
            onChange={handleChangeTask}
          /> 
          <button onClick={onClick}>Send</button>
          <p>{message}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
